server:
  port:  8080


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.pojo


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wyy?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 2

  thymeleaf:
    cache: false