spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wangyi2?characterEncoding=utf-8&useUnicode=true&serverTimezone=GMT&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maxim-pool-sizmue: 2
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  typeAliasesPackage: com.wangyicourse.entity
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
