server:
  port: 7001

spring:
  application:
    name: ORDER-SERVICE  #服务名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  #如果不写defaultZone默认使用8761访问注册中心  #注册的路径（服务器）   将自己的服务注册到这台机器上去
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
feign:
  hystrix:
    enabled: true #开启Hystrix