spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdata?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:  
    hibernate:
      ddl-auto: update
    show-sql: true

#  Jpa.hibernate.ddl-auto:取值有4种：
#create:
#  每次应用启动的时候会重新根据实体建立表，之前的表和数据都会被删除。
#create-drop:
#  和上面的功能一样，但是多了一样，就是在应用关闭的时候，也就是sessionFactory一关闭，会把表删除。
#update:
#  最常用的，第一次启动根据实体建立表结构，之后启动会根据实体的改变更新表结构，之前的数据都在。
#validate:
#  会验证创建数据库表结构，只会和数据库中的表进行比较，不会创建新表，但是会插入新值，运行程序会校验实体字段与数据库已有的表的字段类型是否相同，不同会报错。


#logging:
#  level:
#    com:
#      zxq:  debug
