#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.186.128:3306/dubboDb?useUnicode=true&charactorEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root

#dubbo配置
dubbo:
  #应用名称
  application:
    name: usermanagement-service
  #注册中心地址
  registry:
#    address: zookeeper://192.168.186.128:2181
    address: zookeeper://127.0.0.1:2181
  #服务扫描包
#  scan:
#    base-packages: com.zxq.service
